FROM alpine:3.21
ARG TARGETOS
ARG TARGETARCH
RUN apk add --no-cache ca-certificates \
 && addgroup -S zwoop && adduser -S -G zwoop zwoop
COPY ${TARGETOS}/${TARGETARCH}/zwoop /zwoop
USER zwoop
EXPOSE 8080
ENTRYPOINT ["/zwoop"]
